namespace: khalilgalalem
replicaCount: 1

image:
  repository: nginx
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  ingressClassName: nginx
  host: khalilgalalem-math.horizon-workspaces.com
  tls:
    enabled: true
    secretName: khalilgalalem-math-tls
    clusterIssuer: letsencrypt-prod 

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"