apiVersion: v1
kind: Pod
metadata: 
  name: mathapp-development
  labels:
    app: mathapp-development
    version: "1.0"
    tier: web
    env: horizon
    createdBy: kahlil-galalem
    region: eu-south-1
spec: 
  containers:
  - name: mathapp-development
    image: galalem/golang-mathapp:1.0
    ports:
    - containerPort: 8010
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"