apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: math-pv-claim
  labels:
    app: mathapp-development
spec:
  resources:
    requests:
      storage: 1Gi
  storageClassName: gp2
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce